version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    links:
      - zookeeper
    ports:
      - "9092:9092"
    extra_hosts:
      - "host.gateway:172.17.0.1"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
#      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#  kafka-ui:
#    image: provectuslabs/kafka-ui:latest
#    container_name: kafka-ui
#    ports:
#      - "8880:8080"
#    environment:
#      - KAFKA_CLUSTERS_0_NAME=local
#      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka:9092
#      - KAFKA_CLUSTERS_0_ZOOKEEPER_CONNECT=zookeeper:2181
#    depends_on:
#      - kafka
